### ISSUE TITLE
error in flag_outliers?

### ISSUE THREAD

**Issue by MiKatt** [andschar/standartox#1]
Hi Andreas,

I think it should be 
` fifelse(x < qnt[1] - H | x > qnt[2] + H, TRUE, FALSE)` instead of 
`  fifelse(x < qnt[1] - H | x > qnt[2], TRUE, FALSE)`
in `flag_outliers`. Or is there a reason to use only the upper 75% quantile as upper threshold?

**Comment by andschar** [comment]
Thanks for raising this issue! This is now fixed in the latest version.
